sudo: required
dist: trusty
language: generic

compiler:
  - gcc

install: 
  - cd $HOME
  - git clone https://github.com/grassjelly/opensplice-install
  - cd test
  - ./install
  
notifications:
  email:
    - jimenojmm@gmail.com