#!/usr/bin/env bash

set -e

sudo apt-get update
sudo apt-get install -y gawk flex bison perl gsoap

cd $HOME
git clone https://github.com/PrismTech/opensplice.git
cd opensplice

ARCH=$(uname -i)

if [ $ARCH == "x86_64" ]
    then
        echo "Installing x86_64.linux-dev"
        source ./configure x86_64.linux-dev

else
    echo "Installing armv6l.linux-dev"
    source ./configure armv6l.linux-dev
    exit 1
fi

export INCLUDE_SERVICES_CMSOAP=no

make
make install

echo "alias ospl=\"source $HOME/opensplice/install/HDE/x86_64.linux-dev/release.com\"" >> ~/.bashrc

